trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .azure-pipelines/**

jobs:
- job: static_code_analysis
  displayName: 'Static Code Analysis'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '23.x'

  - script: |
      cd scan-essay
      npm install --legacy-peer-deps
    displayName: 'Install dependencies'

  - script: |
      cd scan-essay
      npx eslint .
    displayName: 'Run ESLint'

  - script: |
      cd scan-essay
      npm audit
    displayName: 'Run security checks with npm audit'

- job: build_image
  displayName: 'Build Image'
  dependsOn: static_code_analysis
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '16.x'

  - script: |
      cd scan-essay
      npm install
    displayName: 'Install dependencies'

  - script: |
      cd scan-essay
      docker build -t scan-essay-app:$(Build.SourceVersion) .
    displayName: 'Build Docker image'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'scan-essay'
      ArtifactName: 'build-artifacts'

  - script: |
      docker run -d -p 8080:8080 scan-essay-app:$(Build.SourceVersion) -e DI_KEY=temp -e DI_KEY=temp -e OPENAI_ENDPOINT=temp
    displayName: 'Run Container'
