name: PR Pipeline - Scan Essay Demo

on:
  pull_request:
    branches:
      - main
      
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd scan-essay
          npm install --legacy-peer-deps

      - name: Run ESLint
        run: |
          cd scan-essay
          npx eslint .

      - name: Run security checks with npm audit
        run: |
          cd scan-essay
          npm audit

  build-image:
    runs-on: ubuntu-latest
    needs: [static-code-analysis]
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd scan-essay
          npm install

      - name: Build Docker image
        run: |
          cd scan-essay
          docker build -t scan-essay-app:${{ github.sha }} .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: scan-essay/

      - name: Run Container
        run: |
          docker run -d -p 8080:8080 scan-essay-app:${{ github.sha }} -e DI_KEY=temp -e DI_KEY=temp -e OPENAI_ENDPOINT=temp
