name: PR Pipeline

on:
  pull_request:
    branches:
      - main
      
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Finds anti-patterns in code
        run: |
          echo "Run Pylint"
      - name: Run security checks
        run: |
          echo "Run Bandit"
  build-image:
    runs-on: ubuntu-latest
    needs: [static-code-analysis]   
    environment: dev 
    steps:
      - uses: actions/checkout@v4      
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Promptflow CLI
        run: |
            python3.11 -m pip install --upgrade pip
            pip3 uninstall -y promptflow promptflow-core promptflow-devkit promptflow-azure
            pip3 install promptflow
            pf --version  

      - name: Install required dependencies
        run: | 
          pip3 cache purge
          pip3 install --upgrade pip setuptools
          pip3 install -r src/requirements.txt

      - name: Create flow docker files
        run: |
              # reference: https://github.com/microsoft/promptflow/tree/main/examples/tutorials/flow-deploy/docker
              pf flow build --source src --output dist --format docker       

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: build-artifacts
            path: dist/

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Image
        env:
          AZURE_CONTAINER_REPOSITORY_NAME: ${{vars.AZURE_CONTAINER_REPOSITORY_NAME}}          
        run: |
            echo "✅ Building docker image..."
            path=dist
            image_tag=$AZURE_CONTAINER_REPOSITORY_NAME:develop-${{ github.sha }}
            echo "Change working directory to $path"
            cd "$path"
            docker build -t "$image_tag" .

      - name: Run Container
        env:
          AZURE_SUBSCRIPTION_ID: ${{vars.AZURE_SUBSCRIPTION_ID}}
          AZURE_LOCATION: ${{vars.AZURE_LOCATION}}
          AZURE_RESOURCE_GROUP: ${{vars.AZURE_RESOURCE_GROUP}}
          AZURE_CONTAINER_REPOSITORY_NAME: ${{vars.AZURE_CONTAINER_REPOSITORY_NAME}}             
        run: |
          echo "✅ Run image..."
          image_tag=$AZURE_CONTAINER_REPOSITORY_NAME:develop-${{ github.sha }}
          docker run -d -p 8080:8080 -e PROMPTFLOW_SERVING_ENGINE=$PROMPTFLOW_SERVING_ENGINE -e PROMPTFLOW_WORKER_NUM=$PROMPTFLOW_WORKER_NUM $image_tag