name: PR Pipeline - Promptflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'prompt-flow-endpoint/**'
      
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Finds anti-patterns in code
        run: |
          echo "Run Pylint"
      - name: Run security checks
        run: |
          echo "Run Bandit"
  build-image:
    runs-on: ubuntu-latest
    needs: [static-code-analysis]   
    environment: dev 
    steps:
      - uses: actions/checkout@v4      
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Promptflow CLI
        run: |
            python3.11 -m pip install --upgrade pip
            pip3 uninstall -y promptflow promptflow-core promptflow-devkit promptflow-azure
            pip3 install promptflow
            pf --version  

      - name: Install required dependencies
        run: | 
          pip3 cache purge
          pip3 install --upgrade pip setuptools
          pip3 install -r prompt-flow-endpoint/requirements.txt

      - name: Create flow docker files
        run: |
              # reference: https://github.com/microsoft/promptflow/tree/main/examples/tutorials/flow-deploy/docker
              pf flow build --source prompt-flow-endpoint --output dist --format docker       

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: build-artifacts
            path: dist/

      - name: Build Image
        run: |
            echo "✅ Building docker image..."
            path=dist
            image_tag=prompt-flow-${{ github.sha }}
            echo "Change working directory to $path"
            cd "$path"
            docker build -t "$image_tag" .

      - name: Run Container
        env:
          PROMPTFLOW_SERVING_ENGINE: "flask"
          PROMPTFLOW_WORKER_NUM: "1"            
        run: |
          echo "✅ Run image..."
          image_tag=develop-${{ github.sha }}
          docker run -d -p 8080:8080 -e PROMPTFLOW_SERVING_ENGINE=$PROMPTFLOW_SERVING_ENGINE -e PROMPTFLOW_WORKER_NUM=$PROMPTFLOW_WORKER_NUM $image_tag